sudo: required

language: java

services:
  - docker
  
script:
  - pwd
  - ls 
  - cd hadoop-hive
  - docker-compose up -d 
  - docker ps -a 
  - docker images
  - docker-compose exec hive-server bash -c "hadoop-hive helloworld!"

after_success:
  - echo 'hadoop docker build/test OK!'